name: Using Actions

on: 
  workflow_dispatch:
env:
  WORK_DIR: my-app
  NODE_VERSION: 20.x

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.WORK_DIR}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Node
        uses: ./.github/actions/composite-deps
        with:
          WORK_DIR: ${{env.WORK_DIR}}
          NODE_VERSION: ${{env.NODE_VERSION}}